### ISSUE TITLE
Cannot build xmp-toolkit 1.7.3 for android

### ISSUE THREAD

**Issue by seok-hong** [adobe/xmp-toolkit-rs#208]
### Expected Behaviour

- build successfully for android cross build on mac

### Reproduce Scenario (including but not limited to)

$ cargo install cross --git https://github.com/cross-rs/cross
$ cargo install cargo-make
$ cargo make android-build
$ cross build --target aarch64-linux-android --release

#### Steps to Reproduce

try to cross build on c2pa-rs repository

#### Platform and Version

MacOS 13.6.6

#### Sample Code that illustrates the problem

N/A

#### Logs taken while reproducing problem

error: failed to run custom build command for `xmp_toolkit v1.7.3`

Caused by:
  process didn't exit successfully: `/target/release/build/xmp_toolkit-458b5156deccf63c/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=build.rs
  > git submodule init

  --- stdout ---

  --- stderr ---
  fatal: not a git repository (or any parent up to mount point /Users/seokhong)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

  > git submodule update

  --- stdout ---

  --- stderr ---
  fatal: not a git repository (or any parent up to mount point /Users/seokhong)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

  COPYING /Users/seokhong/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xmp_toolkit-1.7.3/external/zlib to /Users/seokhong/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xmp_toolkit-1.7.3/external/xmp_toolkit/third-party

  --- stderr
  INFO: building standard FFI for crate
  thread 'main' panicked at /Users/seokhong/.cargo/registry/src/index.crates.io-6f17d22bba15001f/xmp_toolkit-1.7.3/build.rs:167:13:
  Not prepared to build for this OS ("android") yet.
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

**Comment by scouten-adobe** [comment]
@seok-hong just released the log traffic for the git issue is signalling a non-fatal error. In the 1.7.3 release, I changed the behavior so that it logs the git issues but does not stop the build.

The real issue here is the getting the right flags to the C++ build system. As I mentioned earlier, we're not going to be able to focus on this in the near future. If you want to attempt a PR for this (which would be welcomed!), the flags that are in `build.rs` for the currently-supported platforms are adapted from https://github.com/adobe/XMP-Toolkit-SDK/tree/main/build. I'll note that the C++ XMP Toolkit _does_ appear to have Android support, so you may be able to find the right flags and adapt them to the Rust/C++ build system.
