### ISSUE TITLE
DEP_XMP_TOOLKIT_INCLUDE not set in 1.8

### ISSUE THREAD

**Issue by Blonteractor** [adobe/xmp-toolkit-rs#228]
I noticed commit `a98737d` #214 removed the line where `DEP_XMP_TOOLKIT_INCLUDE` was set, I relied on this for building one of my crates. Why was it removed?

**Comment by scouten-adobe** [comment]
Hi @Blonteractor, I went back to the source for the `xmp_toolkit` version 1.7.3 (previous release) and can not find the symbol `DEP_XMP_TOOLKIT_INCLUDE` anywhere in `build.rs` or anywhere else in the `xmp-toolkit-rs` repo, so I don't believe this was an intentional artifact of the build process.

The authors of the `cc` crate made some pretty substantial (dare I say disruptive?) changes to the build process between 1.0.83 and 1.0.86, and I suspect that symbol was defined in the build process from 1.0.83 and before.

The commit you mention is actually for PR #216, which updated the `xmp_toolkit` build process to use the  current (1.0.101 or newer) `cc` crate. I suspect the removal of the symbol was an unintended consequence of that upgrade.

If you can describe why you needed that symbol to be defined, we might be able to add some other, officially-supported mechanism to support your build process going forward.

**Comment by Blonteractor** [comment]
<img width="620" alt="image" src="https://github.com/adobe/xmp-toolkit-rs/assets/48821041/0bcb32db-0773-448e-bb8e-d1bf8b577df4">
Emitting the include directive helps dependent crates to know where to look for the include files, this automatically sets `DEP_XMP_TOOLKIT_INCLUDE` to the value that was emitted. But as you can see it was removed in #216.

**Comment by uttarayan21** [comment]
Yes this was added by me in the pr #187.

**Comment by scouten-adobe** [comment]
@Blonteractor @uttarayan21 sorry for the mix-up. I've merged #229 which restores the include directive (thank you!) and released 1.8.1. That should take care of the issue. Please close if so.

**Comment by uttarayan21** [comment]
Thank you for the quick response. That does indeed fix the issue. 
You can close the issue if you want.
